name: solid_auth_example
description: An example Flutter application to demonstrate authentication to SOLID pods.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  

  solid_auth:
    path: ..

dev_dependencies:

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

dependency_overrides:
  oidc_core:
    git:
      url: https://github.com/kkalass/oidc.git
      ref: fix/oidc-hook-execute-stack-overflow
      path: packages/oidc_core
  