name: solid_auth_example
description: Demonstrate authentication to SOLID pods.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  jwt_decoder: ^2.0.1
  # solid_auth: ^0.1.6
  solid_auth:
    path: ..
  url_launcher: ^6.3.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true
