name: solid_auth_example
description: An example Flutter application to demonstrate authentication to SOLID pods.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  dart_jsonwebtoken: ^2.3.2
  fast_rsa: ^3.4.7
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^0.23.0+1
  intl: ^0.19.0
  jaguar_jwt: ^3.0.0
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.0

  #solid_auth: ^0.1.6
  solid_auth:
    path: ../../solid_auth

dev_dependencies:

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
