name: solid_auth
description: Authentication library to connect to a Solid server from solidproject.org
version: 0.1.28
homepage: https://github.com/anusii/solid_auth

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  clock: ^1.1.2
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.6
  dart_jsonwebtoken: ^3.2.0
  fast_rsa: ^3.8.1
  http: ^1.3.0
  jose: ^0.3.4
  logging: ^1.3.0
  # openid_client: ^0.4.9+1
  openid_client:
    # path: ../openid_client
    git:
      url: https://github.com/anusii/openid_client
      ref: av/custom_edits_for_solid_auth
  openidconnect_web: ^1.0.26
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  web: ^1.1.1

dev_dependencies:
  jwt_decoder: ^2.0.1
  

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  assets:
    - packages/fast_rsa/web/assets/worker.js
    - packages/fast_rsa/web/assets/wasm_exec.js
    - packages/fast_rsa/web/assets/rsa.wasm
