name: solid_auth
description: Authenticate to a Solid server (solidproject.org).
version: 0.1.29
homepage: https://github.com/anusii/solid_auth

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dart_jsonwebtoken: ^3.2.0
  fast_rsa: ^3.8.1
  http: ^1.3.0
  openid_client: ^0.4.9+1
  # openid_client:
  #   git:
  #     url: https://github.com/anusii/openid_client
  #     ref: av/custom_edits_for_solid_auth
  openidconnect_web: ^1.0.26
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  jwt_decoder: ^2.0.1
  # Keep dependency checker quiet.
  solid_auth_example:
    path: example

flutter:
  assets:
    - packages/fast_rsa/web/assets/worker.js
    - packages/fast_rsa/web/assets/wasm_exec.js
    - packages/fast_rsa/web/assets/rsa.wasm
