name: solid_auth
description: Authentication library to connect to a Solid server from solidproject.org
version: 0.1.23
homepage: https://github.com/anusii/solid_auth

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  clock: ^1.1.1
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.3
  fast_rsa: ^3.6.3
  http: ^1.2.2
  intl: ^0.20.2
  jose: ^0.3.4
  jwt_decoder: ^2.0.1
  logging: ^1.2.0
  openidconnect_platform_interface: ^1.0.15
  openidconnect_web: ^1.0.23
  pointycastle: ^3.9.1
  url_launcher: ^6.3.0
  url_launcher_android: ^6.3.5
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^4.0.0

dependency_overrides:
  url_launcher_android: "<=6.0.32"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  assets:
    - packages/fast_rsa/web/assets/worker.js
    - packages/fast_rsa/web/assets/wasm_exec.js
    - packages/fast_rsa/web/assets/rsa.wasm
